wallet: "default" # Replace with your wallet. 
amount_staked: 0.01 # AMount staked per block
amount_unstaked: 0.001 # Amount unstaked per block
validator: "5FFApaS75bv5pJHfAp2FVLBj9ZaXuFDjEypsaBNc1wCfe52v" # Stake to TR21.
ranks_file: "ranks.yaml" 
ranking_beta: 0.25 # How steep your ranking is
drive: 5.0 # How aggressive you stake into the higher ranked subnets.
