name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint --fail-on=W,E,F --exit-zero  ./

      - name: Run Black
        run: |
          black --line-length 79 --exclude '(env|venv|.eggs|.git)' --check .

      - name: Run unit tests
        run: |
          # python -m unittest tests/test_calculate_crps.py
          # python -m unittest tests/test_helpers.py
          python -m unittest tests/test_price_data_provider.py
          python -m unittest tests/test_rewards.py
          python -m unittest tests/test_generate_simulation.py
          # python -m unittest tests/test_miner_data_handler.py
          python -m unittest tests/test_price_simulation.py
